name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          API_HOST: www.vulcan.mpi-internal.com
          SRC_BRANCH: master
        run: ./patch.sh

      - uses: EndBug/add-and-commit@v9
        with:
          add: docs/swagger.json
          message: Update docs
