name: Patch

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: patch
        env:
          API_HOST: www.vulcan.mpi-internal.com
          SRC_BRANCH: master
        run: ./patch.sh

